# Generated by Django 5.2.3 on 2025-06-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/produtos/'),
        ),
    ]
