# Generated by Django 5.2.3 on 2025-06-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0003_produto_categoria_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='local_consumo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
