# Generated by Django 5.2.3 on 2025-06-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0004_pedido_local_consumo_pedido_nome_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('combo', 'Combo'), ('pizza', 'Pizza'), ('lanche', 'Lanche'), ('bebida', 'Bebida'), ('artesanal', 'Artesanal')], max_length=20),
        ),
    ]
