# Generated by Django 5.2.3 on 2025-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0005_alter_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamanhoPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
