# Generated by Django 5.2.3 on 2025-06-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0007_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
