# Generated by Django 5.2.3 on 2025-06-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0008_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamanhopizza',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tamanhopizza',
            name='nome',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
