# Generated by Django 5.2.3 on 2025-06-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0009_tamanhopizza_preco_alter_tamanhopizza_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
