# Generated by Django 5.2.3 on 2025-06-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0010_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
