# Generated by Django 5.2.3 on 2025-07-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0011_itempedido_preco_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='descricao_produto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
