# Generated by Django 5.2.3 on 2025-07-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0013_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('combo', 'Combo'), ('pizza', 'Pizza'), ('lanche', 'Lanche'), ('bebida', 'Bebida'), ('artesanal', 'Artesanal'), ('sabor_promocao', 'Promocao'), ('entrada', 'Entrada')], max_length=20),
        ),
    ]
