# Generated by Django 5.2.3 on 2025-08-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0014_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
