# Generated by Django 5.2.3 on 2025-08-25 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0015_itempedido_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='sabor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_sabor2', to='registrador.produto'),
        ),
    ]
