# Generated by Django 5.2.3 on 2025-08-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0016_itempedido_sabor2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
