# Generated by Django 5.2.3 on 2025-08-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0017_pedido_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
