# Generated by Django 5.2.3 on 2025-10-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0019_alter_pedido_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='valor_total',
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('combo', 'Combo'), ('pizza', 'Pizza'), ('lanche', 'Lanche'), ('bebida', 'Bebida'), ('artesanal', 'Artesanal'), ('sabor_promocao', 'Promocao'), ('entrada', 'Entrada'), ('espeto', 'Espeto')], max_length=20),
        ),
    ]
