# Generated by Django 5.2.3 on 2025-10-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrador', '0021_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('combo', 'Combo'), ('pizza', 'Pizza'), ('lanche', 'Lanche'), ('bebida', 'Bebida'), ('artesanal', 'Artesanal'), ('sabor_promocao', 'Promocao'), ('entrada', 'Entrada'), ('espeto', 'Espeto'), ('porcoes', 'Porções'), ('pf_refeicao', 'PF_Refeição')], max_length=20),
        ),
    ]
